name: PyCheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install ffmpeg
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-print flake8-quotes
    - name: Analysing the code with pylint
      run: |
        flake8 . --count --select=E999 --show-source --statistics
